[features]
seeds = false
skip-lint = false

[programs.localnet]
token_vault = "6VpihCuV526YPTVBNpeTjsaWqoCKDrusbsWXxJ84DtD7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/iddevnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "npx tsx client/*.ts"
